- name: First play
  hosts: dev
  gather_facts: no
  tasks:
    - name: echo hello
      shell: echo "Hello depuis Temporal"

    - name: uptime
      ansible.builtin.shell: uptime

    - name: sleep
      ansible.builtin.wait_for:
        timeout: 5

- name: Second play
  hosts: localhost
  gather_facts: no
  tasks:
    - name: test debug
      debug: 
        var: ansible_facts
